#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# Windows user folder that WSL's /mnt/c/Users/webre maps to.
WIN_SDK="/mnt/c/Users/webre/AppData/Local/Android/Sdk"
ADB="$WIN_SDK/platform-tools/adb.exe"

banner "Oregon Trail Wear — dev environment setup"

# ── Stage 1: Install Android Studio ────────────────────────────────────────
stage "Install Android Studio (on Windows, not WSL)"
say "This project builds via Gradle/NDK from Android Studio running natively on Windows."
open_url "https://developer.android.com/studio"
step "Download the Windows installer and run it."
step "Accept the defaults through the setup wizard (Standard install type is fine)."
pause "Press Enter once the installer finishes and the Android Studio welcome screen appears."

if [[ -e "/mnt/c/Program Files/Android/Android Studio/bin/studio64.exe" ]]; then
  note "✓ found Android Studio at the default install location"
else
  warn "didn't see Android Studio at the default path — if you installed elsewhere that's fine, just continue"
fi

# ── Stage 2: NDK + CMake components ─────────────────────────────────────────
stage "Install the NDK and CMake components"
say "These aren't installed by default — the project's native build (AppleWin core) needs both."
step "In Android Studio: More Actions → SDK Manager (or Tools → SDK Manager if a project is open)."
step "Open the 'SDK Tools' tab."
step "Check 'NDK (Side by side)' and 'CMake', then click Apply and let it install."
pause "Press Enter once the NDK and CMake install finishes."

if [[ -d "$WIN_SDK/ndk" ]] && [[ -n "$(ls -A "$WIN_SDK/ndk" 2>/dev/null)" ]]; then
  note "✓ found an NDK version under $WIN_SDK/ndk"
else
  warn "didn't find $WIN_SDK/ndk — if your SDK lives at a different path that's fine, just continue"
fi

# ── Stage 3: Windows Developer Mode ─────────────────────────────────────────
stage "Enable Windows Developer Mode"
say "AppleWin's root CMakeLists.txt creates a symlink unconditionally on every configure."
say "Without Developer Mode (or running as admin), that symlink call fails and the build won't configure."
open_url "ms-settings:developers"
step "If that didn't open Settings directly: Settings → Privacy & security → For developers."
step "Turn on 'Developer Mode' and accept the warning dialog."
pause "Press Enter once Developer Mode is switched on."

# ── Stage 4: Watch developer options ────────────────────────────────────────
stage "Enable Developer options on the Pixel Watch 2"
say "Do this on the watch itself."
step "Settings → System → About → tap 'Build number' 7 times (until it says you're a developer)."
step "Back out to Settings → Developer options."
step "Turn on 'ADB debugging'."
step "Turn on 'Wireless debugging', then open it and note the IP address and port it shows,"
say "  plus tap 'Pair new device' to get a 6-digit pairing code and a separate pairing IP:port."
pause "Press Enter once ADB debugging and Wireless debugging are both on and you can see the pairing screen."

# ── Stage 5: Pair and connect over ADB ──────────────────────────────────────
stage "Pair the watch over Wi-Fi and verify with adb"
if [[ -x "$ADB" ]]; then
  note "✓ found adb at $ADB"
else
  warn "didn't find adb at $ADB — adjust the WIN_SDK path at the top of this script if your SDK lives elsewhere"
fi

say "Watch and computer must be on the same Wi-Fi network."
ask WATCH_PAIR_ADDR "Pairing IP:port shown on the watch's 'Pair new device' screen:"
ask WATCH_PAIR_CODE "6-digit pairing code shown there:"
if [[ -x "$ADB" ]]; then
  say "Running: adb pair $WATCH_PAIR_ADDR"
  "$ADB" pair "$WATCH_PAIR_ADDR" "$WATCH_PAIR_CODE" || warn "pairing failed — re-check the code/address and try again"
else
  warn "skipping automatic pairing since adb wasn't found — run 'adb pair $WATCH_PAIR_ADDR' yourself"
fi

ask WATCH_CONNECT_ADDR "Main Wireless debugging IP:port (shown on the same screen, different from the pairing port):"
if [[ -x "$ADB" ]]; then
  "$ADB" connect "$WATCH_CONNECT_ADDR" || warn "connect failed — double check the watch is still on that screen"
  say "Devices adb currently sees:"
  "$ADB" devices
fi

if confirm "Does 'adb devices' show your watch as 'device' (not 'unauthorized' or 'offline')?"; then
  note "✓ watch connected"
else
  warn "check for an authorization prompt on the watch itself, or re-run this stage"
fi

# ── Stage 6: Open the project ───────────────────────────────────────────────
stage "Open the project in Android Studio"
say "The project lives at C:\\Users\\webre\\oregon-trail-wear-os on the Windows side."
step "Android Studio → Open → select that folder."
step "Let Gradle sync. Per README-NEXT-STEPS.md, expect version-resolution issues on first sync —"
say "  those are Kotlin/Compose dependency versions guessed without a live Maven lookup."
note "Tip: comment out the externalNativeBuild block in app/build.gradle.kts for the first sync,"
note "so Kotlin/Compose issues are visible before tackling the NDK/CMake build separately."
pause "Press Enter once Gradle sync completes (errors and all — that's expected on a first pass)."

finish
say "Next: work through README-NEXT-STEPS.md's 'Suggested order' section for the NDK/CMake build itself."
